MTU-tests/Makefile
MTU-tests/README.org
MTU-tests/encap.h
MTU-tests/tc_bpf_inc_pkt_size.c

Simple TC-BPF program for testing different packets sizes that violate the MTU of the interface.
This is part of testing upstream kernel work, for removing the MTU limit in the BPF-helpers that change packet size, and instead add BPF-helper that can check or lookup interface MTU.

MTU testing

---

MTU-tests/Makefile
MTU-tests/tc_mtu_enforce.c

I'm developing new BPF-helper bpf_check_mtu() for the kernel, but it's not accepted upstream (yet).
Simple test showing how I can still test this, by manually defining the call signature.
Unsure how to handle when this gets accepted upstream, as there will be a compile conflict once the BPF-helper signature becomes avail via updating libbpf (via git-submodule).

MTU-tests: Add some external use of BPF-helper bpf_check_mtu

---

pping/TODO.md
pping/pping.c
pping/pping.h
pping/pping_helpers.h
pping/pping_kern_tc.c
pping/pping_kern_xdp.c

Hi @tohojo,
Been working a little bit on adding IPv6 support to pping and now got it to a working stage. So thought I would start a pull request so you can provide some feedback on it.
I use `struct in6_addr` to store both IPv6 and IPv4 addresses, by mapping IPv4 addresses to the IPv6 range as we've talked about previously. I'm not entierly sure I do the mapping correctly, however as I'm also the one who does the "unmapping" it seems to work. Still, it would be great if you could take a look at that. 
I've also renamed some things to move away a bit from just TCP timestamps and be more general, so that pping can be extended to support different protocols in the future (as we've also talked about). There's still much more do be done in this area though, and my focus has mainly been on …

pping: Add IPv6 support

---

lib/util/json_writer.c
lib/util/json_writer.h
lib/util/util.mk
pping/Makefile
pping/README.md
pping/TODO.md
pping/pping.c
pping/pping.h
pping/pping_kern.c

These commits update the standard output format to be equivalent with Kathie's pping standard format, which means it adds a timestamp (pushed from the XDP program) and min-RTT (adds in-kernel tracking of minimum RTT for each flow). Furthermore, I've added a simple JSON format as well as Kathie's "machine friendly" format (used by ppviz).
TODOs:
- Currently the program my report incorrect minimum-RTT if the tc program deletes the flow-information before the XDP program can calculate the RTT of a packet from that flow. Couple of options for fixes would be to only attempt to delete flow-information from the XDP program, or include the current min-RTT into the stored packet timestamp. 
- Update `README` and `TODO`

Pping better output

---

headers/vmlinux/arch/arm64/vmlinux.h
headers/vmlinux/arch/powerpc/vmlinux.h
headers/vmlinux/arch/x86/vmlinux.h
headers/vmlinux/vmlinux_common.h
headers/vmlinux/vmlinux_net.h
headers/vmlinux/vmlinux_types.h
headers/vmlinux_local.h
ktrace-CO-RE/Makefile
ktrace-CO-RE/README.org
ktrace-CO-RE/ktrace01.c
ktrace-CO-RE/ktrace01_kern.c
lib/common.mk

"Learning by doing":
- Learning what CO-RE can do via writing a simple kprobe tracing program use some of these features.
I had to change the Makefile system to handle `SEC("kprobe")` and macro `BPF_KPROBE` as compiling with `-target bpf` result in `PT_REGS_PARM1` not being defined. As `include <bpf/bpf_tracing.h>` cannot determine the ARCH from compiler defines.
To solve this detect the `ARCH` our makefile system in [file lib/common.mk](../lib/common.mk) (via `uname -m`) and defines the `__TARGET_ARCH_$(ARCH)` in `BPF_CFLAGS`.
This PR also contains some `vmlinux.h` header variants for a number of ARCHs.
Choose to splitup `vmlinux_*.h` headers and only include what was needed for this example.
We will see how much maintenance this cause, and if this is the case we can consider adding the …

BPF example with ktrace and CO-RE

---

AF_XDP-interaction/README.org
AF_XDP-interaction/af_xdp_kern.c
AF_XDP-interaction/af_xdp_user.c

Describe **why** XDP RX-timestamps are essential for AF_XDP.
Also add some data-point results from different systems, measuring the latency between RX-softirq and AF_XDP processing.
Even-though, as explained, this latency is not important to the real use-case in question. The essential part is moving the time-stamping to XDP, as it makes is possible for the application to relax the latency requirements and process RX-packets in bulk.

AF_XDP example added some results

---

AF_XDP-interaction/af_xdp_user.c
AF_XDP-interaction/common_defines.h
AF_XDP-interaction/common_params.c
AF_XDP-interaction/lib_checksum.h

The main customer use-case for the AF_XDP example is actually accurately periodic transmits, for matching a Time-Triggered Ethernet schedule.
In this PR we don't handle the time-sync or schedule, we only demonstrate periodic TX-cyclic sending.

AF_XDP-interaction: Implement TX-cyclic sending

---

AF_XDP-interaction/af_xdp_user.c
AF_XDP-interaction/common_defines.h
AF_XDP-interaction/common_params.c
AF_XDP-interaction/common_params.h

Measurements show that on test systems, clock_nanosleep fairly consistently wakeup later (or after) the requested sleep time.
In this branch I've been playing with improving on wake-up accuracy for cyclic-TX.
Mainly creating this for @jopbs to notice ;-)

AF_XDP example: Improvements to wake-up accuracy

---

pping/pping.c

PPing previously only shut down gracefully on SIGINT, but did not handle SIGTERM which is the most common signal for killing a process non-interactively. Here I address that by simply adding the same signal-handler for the SIGTERM signal.
It may be worth considering if there are additional signals that should also be handled similarly, ex SIGHUP or SIGQUIT.
While not directly related, while I still remeber it @tohojo also suggested detecting if pping was already running on the interface, and then handle that. Is the correct way to do that to check for BPF-programs with the same name already attached to the interface and if found simply abort and inform the user that pping is already running?

pping: Add graceful shutdown on SIGTERM

---

pping/Makefile
pping/TODO.md
pping/pping.c
pping/pping.h
pping/pping_debug_cleanup.h
pping/pping_kern.c

These commits moves the cleanup logic for stale entires from userspace to a BPF iter program. So instead of userspace periodically looping through the maps clearing out old entries, it only triggers the BPF programs periodically, and the BPF program iterates through all the entries removing  those which are considered old.
Also adds some slightly more complex logic for when an entry can be removed, for example ICMP flows and unopened TCP flows can be cleared faster than an open TCP flow, and timestamp entries with low RTTs can be cleared much faster than the static 10s limit.
All these commits were created with the changes from [PR#23](https://github.com/xdp-project/bpf-examples/pull/23) in mind, more specifically with those that are now in …

PPing - Improve map cleanup

---

pping/TODO.md
pping/pping.h
pping/pping_kern.c

An attempt to improve the performance of ePPing by avoiding unnecessary lookups in the timestamp map. Instead of looking for matching timestamp for every (valid) packet, only look for matches in case we know there are unmatched timestamps for the flow.
I think it already works, but may still need some cleanup or other fixes before this is ready to be merged.

PPing optimization: Tracking outstanding timestamps

---

pping/pping.c
pping/pping.h
pping/pping_kern.c

Attempt at optimizing ePPing by only doing a single map lookup to get flow state for both directions of the flow (down from two lookups, one for each direction). This is accomplished by placing the flow state from both directions into a single map entry, and using a common key (in this case created by sorting the flow tuple) for lookup.
The first two commits are just minor refactors. I guess they're not really related to this PR, so could break it out into a separate PR if requested. 
The third commit contains the change merging the flow state for both directions into a single map entry. This has some implications of how flow states are created, deleted and looked up, which affects both the ingress/egress programs as well as the periodical cleanup programs. Therefore, this commit contains …

PPing dualdirection flowstate

---

.gitmodules
configure
lib/.gitignore
lib/Makefile
lib/common.mk
lib/install/.gitignore
lib/install/include/.gitignore
lib/install/lib/.gitignore
lib/util/Makefile
lib/util/logging.c
lib/util/logging.h
lib/util/util.mk
nat64-bpf/nat64.c

This adds support for embedding libxdp and linking userspace binaries against it. It relies on recent changes in the xdp-tools repository to support this.
There's one outstanding issue with this: the embedded version of libxdp needs to be able to find the dispatcher BPF object, which it is not able to do with the custom install path currently. This needs to be fixed in upstream libxdp.

Embedding libxdp

---

AF_XDP-interaction/Makefile
AF_XDP-interaction/af_xdp_user.c
AF_XDP-interaction/btf_unit_test.c
AF_XDP-interaction/btf_unit_test_bpf.c
AF_XDP-interaction/lib_xsk_extend.c

Add BTF unit test type program for decoding the BTF info in userspace.
And general cleanups.
I want to remove the "hashmap" code (*but didn't have time*), as it is not being used in this code example (and only adds confusion).
- The "hashmap" code introduce runtime overhead, when looking up struct members.
- The code example show how "hashmap" is not necessary, by having `struct xsk_btf_member` store offset and size.
- Via `struct xsk_btf_member` we get faster code by doing lookups at "setup-time" and let runtime use offset+size directly

Cleanups for AF_XDP-interaction code

---

pping/pping_kern.c

While refactoring the code use the dual-flow state (keep state for both directions in a single entry), the incrementing of the debug counter for timed out (deleted by periodical cleanup) flow states was accidentally removed. Add it back in again.

pping: Add missing debug timeout count

---

BTF-playground/Makefile
BTF-playground/btf_module_ids.c
BTF-playground/btf_module_read.c

Userspace code (libbpf based) experimenting with looking up the Kernel's BTF **object** *ID* for kernel modules.
This is needed as part of the XDP-hints effort as we are looking at having a "full" u64 BTF ID that comprise of the BTF object ID + BTF type ID (inside the object ID).
- This is done to be able to fully identify which kernel module created the BTF ID.

BTF playground for extracting Kernel BTF object ID

---

BTF-playground/btf_module_ids.c
BTF-playground/btf_module_read.c
Makefile
bpf-link-hang/bpf-link-hang.c
headers/linux/btf.h
ktrace-CO-RE/ktrace01.c
nat64-bpf/nat64.c
preserve-dscp/preserve-dscp.c
traffic-pacing-edt/xdp_cpumap_loader.c

Newer kernels got a new BTF type "kind" (BTF_KIND_ENUM64) and needs a newer libbpf version, else it fails decoding BTF provided by the Linux kernel.
Running libbpf with verbose/debug print statements shows this error:
```
libbpf: Unsupported BTF_KIND:19
libbpf: loading kernel BTF '/boot/vmlinux-5.19.0-bpf-next-xdp-hints+': -22
libbpf: failed to find valid kernel BTF
```
Before we can upgrade the libbpf version, we need to fixup the bpf-examples to use the newer APIs. This PR is a step in that direction, meaning the API conversion isn't fully done.

Prepare for newer libbpf in bpf-examples

---

AF_XDP-example/Makefile
AF_XDP-example/README.org
AF_XDP-example/xdpsock.c
AF_XDP-example/xdpsock.h
AF_XDP-example/xdpsock_kern.c
AF_XDP-forwarding/Makefile
AF_XDP-forwarding/README.org
AF_XDP-forwarding/xsk_fwd.c
Makefile

These two commits adds the two AF_XDP samples that were removed from Linux as libbpf got its xsk support deprecated. These are xdpsock and xsk_fwd. They are pretty much brought over untouched, though I have added a README file for both of them, to make using them simpler. xdpsock is now AF_XDP-example and xsk_fwd is AF_XDP-forwarding.

Add samples from Linux

---

pping/TODO.md
pping/pping_kern.c

This PR fixes a potential issue that could cause ePPing to report incorrect RTTs (due to failing to only create a single timestamp per unique TSval). This issue would mainly manifest if the RTT < 1ms, as otherwise the entry in the timestamp map would block other entries with the same TSval from being created. See commit message (and the removed part of the TODO in the second commit) for more details.
This commit adds a little bit of overhead in the form of two `bpf_ntohl()` calls and some more complicated operations for checking if a TSval differs from a previous one (two subtractions (which I suspect the compiler to optimize to one), and two comparisons, plus a check for protocol replaces a single equality comparison). While I have not run any tests to measure the performance impact I do …

PPing fix reorder issue

---

pping/pping_kern.c

I had accidently set the ifindex incorrectly for the XDP program in [the commit that made the packet parsing global functions](https://github.com/xdp-project/bpf-examples/commit/add888566d110f4a6c79e558b1e0eb6ef84d5bc3). This broke the localfilt functionality when using the XDP ingress hook, as the FIB lookup would fail (or potentially be for the wrong ifindex). So this tiny PR fixes that.

pping: Fix XDP ingress ifindex

---

pping/pping.c
pping/pping.h
pping/pping_kern.c

Add an option for ePPing to ignore TCP SYN packets, so that the
initial handshake phase of the connection is ignored. More details in the commit message.
For now I've only made it an opt-in option, and by default ePPing will still track SYN-packets, and any SYN-flood attacks would cause it to fall apart. The trace used in the paper ["Continuous in-network round-trip time monitoring"](https://dl.acm.org/doi/10.1145/3544216.3544222) suggests that incomplete TCP connections are quite common, so it might be worth considering if ignoring the SYN packets should be the default option.

PPing: Add option to ignore SYN-packets

---

pping/pping.c

A few unrelated minor fixes to the userspace component of ePPing. Threw them together in the same PR to avoid lots of tiny PRs.
- The first commit fixes an issue where the clsact would not be cleaned up if using tc mode (--ingress-hook tc)
- The second commit adds a small hint suggesting trying a newer kernel or using tc mode if it fails loading the XDP program. This addresses #49.
- The third commit simply adds a couple of calls to `bfp_object__close()` on shutdown/error. I'm not sure if this is really needed when the program ends directly after anyways, but most recent examples seem to do it so figured I'd better do it as well in case it cleans up some resources that's not automatically freed by the kernel when the program ends.
As for the second commit, I'm not sure if it's the best …

PPing minor userspace fixes

---

AF_XDP-forwarding/xsk_fwd.c

Issue #78 exposes a problem in that eths which do not support 'zerocopy' cause socket initialization to fail. The fix for this is to drop XDP_ZEROCOPY from the bind flags; this causes libxdp to first try to set up zerocopy mode and it this fails to fall back to copying the packet data.
Signed-off-by: Chris Ward <tjcw@uk.ibm.com>

Arrange for bind for eth to fall back to 'copy' if 'zerocopy' is not supported

---

preserve-dscp/preserve_dscp_kern.c

The old "classifier/xxx" format is no longer supported.

preserve-dscp: update for strict section names

---

configure

The system libbpf check would unconditionally fail with a modern libbpf because the example program used outdated and removed library functions. Update the test program so that system libbpf check can pass again.

configure: update libbpf check for modern api

---

.gitmodules

Make Git ignore untracked files in libxdp submodule, as it's just annoying. "Dirty" changes were already ignored in the libbpf submodule, and I see no reason why they shouldn't also be ignored for libxdp.

Ignore dirty libxdp submodule

---

pping/lhist.h
pping/pping.c
pping/pping.h
pping/pping_kern.c

This PR adds an initial simple version of aggregating RTTs (instead of dumping every single RTT sample as normally done). It aggregates all RTTs (no option to filter or group the aggregation yet) by adding all samples to a histogram and keeping track of minimum and maximum RTT.
The histogram is of fixed size (`pping.h:AGG_RTT_NR_BINS`) and uses equally wide bins (`pping.h:AGG_RTT_BIN_WIDTH`). The current setting is 1000 bins that are 0.1 ms wide, allowing ePPing to capture RTTs from 0-100ms with 0.1ms resolution (the last bin is half-open, so RTTs > 100 ms will also go there). There is currently no option to configure the histogram from the command line, but it would be easy to at least make the bin-width configurable (nr of bins is trickier as it affects the size of structs used in the …

Add aggregation option to ePPing

---

configure

For ARM64/AArch64 based systems, as linux header files reside under architecture specific directories, this PR fixes configure script to include right header files.

Fix compilation error for arm64

---

AF_XDP-example/xdpsock.c
AF_XDP-example/xdpsock_kern.c
headers/linux/if_xdp.h

* Add support for handling multi-buffer packets.
* Add a new CLI option to enable frag support.
* xdpsock_kern.c is modified to use num_socks as updated by userspace application.
* MAX_PKT_SIZE is set as 9728 as supported by many NICs.
* xdpsock_kern.o is loaded for both frags and shared uemem cases.

AF_XDP-example: add multi-buffer support to xdpsock

---

pping/TODO.md
pping/pping.c
pping/pping.h
pping/pping_kern.c

Add some additional packet counters to ePPing, to provide a more complete picture of the encountered traffic.
Overall, the plan is to:
- Have 3 sets of packet/byte counters on a per-prefix level: 
- TCP with timestamp
- TCP without timestamp
- Other (non-TCP)
- Have global per-protocol packet counters
- Will still likely have to go with some selection of common-ish protocols, as just going going with the value from the IP-header protocol/next-header field gives you some 145 actual protocols (and another 111 invalid/reserved ones). 
- It's probably also good to have a counter for non-IP as well as non-Ethernet packets (these will not really be possible to add to the per-prefix stats, as they won't have a valid IP-address)
- Change current debug counters on map utilization to be included in …

Add additional counters to ePPing

---

pping/TODO.md
pping/pping.c
pping/pping.h
pping/pping_kern.c

Add counters for the 4 ECN code points to the global counters.
This builds on top of PR #100 as it makes use of the global counters that is added there, and makes no sense to merge without first merging #100. I can rebase this whenever #100 is merged.

Add ECN counters to ePPing

---

Makefile
headers/vmlinux/vmlinux_common.h
headers/vmlinux/vmlinux_net.h
xdp-synproxy/Dockerfile
xdp-synproxy/Makefile
xdp-synproxy/README.org
xdp-synproxy/install-rules.sh
xdp-synproxy/uninstall-rules.sh
xdp-synproxy/xdp-synproxy-daemonset.yaml
xdp-synproxy/xdp_synproxy.c
xdp-synproxy/xdp_synproxy_kern.c

this code is from kernel bpf selftests xdp synproxy, removed the tc part for simplicity, shows an exmaple of using libxdp to attach xdp synproxy program on network interface.
if port is not in allowed ports, the packet will be dropped by xdp synproxy by default, this would break tcp connections to ports that user does not want to do synproxy, change the default to allow connection pass through.

Add xdp-synproxy to bpf-examples

---

headers/vmlinux/vmlinux_net.h
xdp-synproxy/README.org
xdp-synproxy/xdp_synproxy_kern.c

from [Bug in xdp synproxy kernel code](https://marc.info/?t=170084715900001&r=1&w=2), a bug is found when xdp synproxy is required to handle SYNACK from backend server,  and fix is accepted in kernel, sync the fix here. 
also add doc on adding iptables SYNPROXY in filter table FORWARD chain, and attach the xdp synproxy to the client side/internet side router/firewall interface to accelerate synproxy in XDP to protect backend server

Sync in kernel bpf selftest xdp synproxy fix: erroneous bitmask operation

---

xdp-synproxy/xdp_synproxy_kern.c

sync kernel commit 977bc146d (selftests/bpf: track tcp payload offset as scalar in xdp_synproxy).
without above fix, when run xdp-synproxy in kernel 6.7, it failed with verifier: "BPF program is too large. Processed 1000001 insn"

track tcp payload offset as scalar in xdp_synproxy

---

configure

The xdpsock needs libcap, otherwise it will compile failed. So we can add the libcap check in configure.
xdpsock.c:27:10: fatal error: sys/capability.h: No such file or directory
27 | #include <sys/capability.h>
|          ^~~~~~~~~~~~~~~~~~
The test result:
dylane@2404:~/sdb/bpf-examples$ ./configure
clang: 18.1.3 (1ubuntu1)
libcap support: yes
libmnl support: yes
libbpf support: submodule
ELF support: yes
zlib support: yes
libxdp support: submodule

configure: Add libcap check

---

headers/vmlinux/vmlinux_net.h
netstacklat/fill_filter_maps.sh
netstacklat/netstacklat.bpf.c
netstacklat/netstacklat.c
netstacklat/netstacklat.h
netstacklat/netstacklat.yaml

Hi @tohojo and @netoptimizer. This is only draft PR for now to facilitate some discussion. For a real PR I imagine we break this down into some smaller chunks (this is 4 different branches stacked on top of each other). Each of those essentially deals with:
- Change the socket enqueue hook because the one I used had some issues
- Multiplex all histograms into a single hashmap (needed for the grouping support, and is generally more convenient)
- Additional filtering options (ifindex, network namespace and cgroup. TODO: add filter for non-empty socket rx queues)
- Groupby support (ifindex and cgroups)
So I do not expect you to review this in detail as of now (although if you have nothing better to do feel free to do so, do not have any major cleanup planned). I would however like some …

Netstacklat: Add filtering and grouping

---

AF_XDP-example/xdpsock.c

The xdpsock tool currently documents a --frags option, but only the short -F flag was actually supported by the option parser. This caused a mismatch between the advertised CLI usage and the actual behavior.
Fix this by adding the missing --frags long option, making the CLI consistent and preventing user confusion.

fix(xdpsock): correct long option for frag support (--frags)
